[package]
name = "groth16-verifier"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-groth16 = { path = "../../../../risc0/groth16", default-features = false, features = ["std"] }
risc0-zkvm = { path = "../../../../risc0/zkvm", default-features = false, features = ["std", "unstable"] }

[patch.crates-io]
substrate-bn = { git = "https://github.com/risc0/paritytech-bn", tag = "v0.6.0-risczero.0" }
