[package]
name = "verifier"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
borsh = { version = "1.5.7", default-features = false }
risc0-zkvm = { path = "../../../risc0/zkvm", default-features = false }
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3", features = ["console"] }


