[package]
name = "verifier"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
borsh.workspace = true
risc0-zkvm = { workspace = true }
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3", features = ["console"] }


