[package]
name = "prover-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
postcard = "1.1.1"
risc0-zkvm = { path = "../../risc0/zkvm", features = ["prove", "unstable"] }
risc0-zkvm-methods = { path = "../../risc0/zkvm/methods/" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
workerpool = "1.2"

[dev-dependencies]
test-log = "0.2.17"

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
