[alias]
risc0 = "run --bin cargo-risczero -- risczero"
xfast = "run --package xtask --no-default-features --"
xtask = "run --package xtask --release --"

[build]
rustflags = ["-Dclippy::all", "-Dwarnings", "-Ctarget-cpu=native"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
