[package]
name = "risc0-r0vm"
description = "RISC Zero zero-knowledge VM executable"
version = "3.0.0"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1.0.98"
bincode = "1.3"
bytemuck = "1.12"
clap = { version = "4.5", features = ["derive", "env"] }
kameo = { version = "0.16", features = ["remote"] }
multi_index_map = "0.13.0"
opentelemetry = "0.29.1"
opentelemetry-otlp = "0.29.0"
opentelemetry_sdk = "0.29.0"
opentelemetry-stdout = { version = "0.29.0", features = ["trace"] }
risc0-circuit-rv32im = { workspace = true }
risc0-zkvm = { workspace = true, features = ["prove"] }
serde = { version = "1.0.219", features = ["rc"] }
tokio = { version = "1.44.2", features = [
  "macros",
  "rt-multi-thread",
  "signal",
] }
tokio-util = "0.7.15"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
anyhow = "1.0"
assert_cmd = "2.0"
assert_fs = "1.0"
risc0-zkvm-methods = { path = "../zkvm/methods" }
temp-env = "0.3"
test-log = { version = "0.2", default-features = false, features = ["trace"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
disable-dev-mode = ["risc0-zkvm/disable-dev-mode"]
dual = ["risc0-zkvm/dual"]
metal = ["risc0-zkvm/metal"]
redis = ["risc0-zkvm/redis"]
r0vm-ver-compat = ["risc0-zkvm/r0vm-ver-compat"]
