[package]
name = "risc0-r0vm"
description = "RISC Zero zero-knowledge VM executable"
version = "3.0.0"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1.0.98"
bincode = "1.3"
bytemuck = "1.12"
clap = { version = "4.5", features = ["derive", "env"] }
kameo = { version = "0.16", features = ["remote"] }
risc0-circuit-rv32im = { workspace = true }
risc0-zkvm = { workspace = true, features = ["prove"] }
serde = "1.0.219"
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
anyhow = "1.0"
assert_cmd = "2.0"
assert_fs = "1.0"
risc0-zkvm-methods = { path = "../zkvm/methods" }
temp-env = "0.3"
test-log = { version = "0.2", default-features = false, features = ["trace"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
disable-dev-mode = ["risc0-zkvm/disable-dev-mode"]
dual = ["risc0-zkvm/dual"]
metal = ["risc0-zkvm/metal"]
redis = ["risc0-zkvm/redis"]
r0vm-ver-compat = ["risc0-zkvm/r0vm-ver-compat"]
